export const USER = [
  {
    id: 1,
    label: "First name",
    key: "firstName",
    type: "password",
    value: "",
    required: true,
    disabled: false,
    placeholder: "",
    errorMsg: "",
    error: false,
    labelInside: false,
    showLabel: true,
  },
  {
    id: 2,
    label: "Last name",
    key: "lastName",
    type: "text",
    value: "",
    required: true,
    disabled: false,
    placeholder: "",
    errorMsg: "",
    error: false,
    labelInside: false,
    showLabel: true,
  },
  {
    id: 3,
    label: "Email address",
    key: "email",
    type: "email",
    value: "",
    required: true,
    disabled: false,
    placeholder: "",
    errorMsg: "",
    error: false,
    labelInside: false,
    showLabel: true,
  },
  {
    id: 4,
    label: "Store name",
    key: "storeName",
    type: "text",
    value: "",
    required: true,
    disabled: false,
    placeholder: "",
    errorMsg: "",
    error: false,
    labelInside: false,
    showLabel: true,
  },
  {
    id: 5,
    label: "code",
    key: "code",
    type: "text",
    value: "",
    required: false,
    disabled: false,
    placeholder: "+99",
    errorMsg: "",
    error: false,
    labelInside: true,
  },
  {
    id: 6,
    label: "Mobile",
    placeholder: "",
    key: "mobile",
    type: "text",
    value: "",
    required: false,
    disabled: false,
    errorMsg: "",
    error: false,
    labelInside: true,
  },
  {
    id: 7,
    label: "Create password",
    placeholder: "",
    key: "password",
    type: "password",
    value: "",
    required: false,
    disabled: false,
    errorMsg: "",
    error: false,
    labelInside: true,
  },
  {
    id: 8,
    label: "confirm password",
    placeholder: "",
    key: "confirmPassword",
    type: "password",
    value: "",
    required: false,
    disabled: false,
    errorMsg: "",
    error: false,
    labelInside: true,
  }, {
    id: 9,
    label: "Enter password",
    placeholder: "",
    key: "password",
    type: "password",
    value: "",
  },
];

export const initialState = {
  values: {
    firstName: "",
    lastName: "",
    email: "",
    code: '',
    password: '',
    confirmPassword: '',
    disable: true,
    editOption: 'create'
  },
  errors: {
    firstName: "",
    lastName: "",
    email: "",
    code: '',
    password: '',
    confirmPassword: '',
  },
}